# 1. Data Collection and Exploration

In [1]:
# import the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:

# Display all columns (Pandas shows all columns.)
pd.set_option("display.max_columns", None)

# Better plot size (This sets the default size of every Matplotlib graph.)
plt.rcParams["figure.figsize"] = (12,6)

# Step 2: Load the datasets

In [3]:
train = pd.read_csv("../data/train.csv")
stores = pd.read_csv("../data/stores.csv")
holidays = pd.read_csv("../data/holidays_events.csv")
oil = pd.read_csv("../data/oil.csv")
transactions = pd.read_csv("../data/transactions.csv")

# Step 3: Preview the datasets

In [4]:
train.head()

   id        date  store_nbr      family  sales  onpromotion
0   0  2013-01-01          1  AUTOMOTIVE    0.0            0
1   1  2013-01-01          1   BABY CARE    0.0            0
2   2  2013-01-01          1      BEAUTY    0.0            0
3   3  2013-01-01          1   BEVERAGES    0.0            0
4   4  2013-01-01          1       BOOKS    0.0            0

In [5]:
stores.head()

   store_nbr           city                           state type  cluster
0          1          Quito                       Pichincha    D       13
1          2          Quito                       Pichincha    D       13
2          3          Quito                       Pichincha    D        8
3          4          Quito                       Pichincha    D        9
4          5  Santo Domingo  Santo Domingo de los Tsachilas    D        4

In [7]:
holidays.head()

,date,type,locale,locale_name,description,transferred
0,2012-03-02,Holiday,Local,Manta,Fundacion de Manta,False
1,2012-04-01,Holiday,Regional,Cotopaxi,Provincializacion de Cotopaxi,False
2,2012-04-12,Holiday,Local,Cuenca,Fundacion de Cuenca,False
3,2012-04-14,Holiday,Local,Libertad,Cantonizacion de Libertad,False
4,2012-04-21,Holiday,Local,Riobamba,Cantonizacion de Riobamba,False

In [8]:
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20

In [9]:
transactions.head()

         date  store_nbr  transactions
0  2013-01-01         25           770
1  2013-01-02          1          2111
2  2013-01-02          2          2358
3  2013-01-02          3          3487
4  2013-01-02          4          1922

# Step 4: Dataset dimensions

In [10]:
print("Train:", train.shape)
print("Stores:", stores.shape)
print("Holidays:", holidays.shape)
print("Oil:", oil.shape)
print("Transactions:", transactions.shape)

Train: (3000888, 6)
Stores: (54, 5)
Holidays: (350, 6)
Oil: (1218, 2)
Transactions: (83488, 3)

# Step 5: Check data types

In [19]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         str
 2   store_nbr    int64
 3   family       str
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), str(2)
memory usage: 137.4 MB

In [12]:
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   store_nbr  54 non-null     int64
 1   city       54 non-null     str
 2   state      54 non-null     str
 3   type       54 non-null     str
 4   cluster    54 non-null     int64
dtypes: int64(2), str(3)
memory usage: 2.2 KB

In [13]:
holidays.info()

<class 'pandas.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         350 non-null    str
 1   type         350 non-null    str
 2   locale       350 non-null    str
 3   locale_name  350 non-null    str
 4   description  350 non-null    str
 5   transferred  350 non-null    bool
dtypes: bool(1), str(5)
memory usage: 14.1 KB

In [14]:
oil.info()

<class 'pandas.DataFrame'>
RangeIndex: 1218 entries, 0 to 1217
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1218 non-null   str
 1   dcoilwtico  1175 non-null   float64
dtypes: float64(1), str(1)
memory usage: 19.2 KB

In [15]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 83488 entries, 0 to 83487
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   date          83488 non-null  str
 1   store_nbr     83488 non-null  int64
 2   transactions  83488 non-null  int64
dtypes: int64(2), str(1)
memory usage: 1.9 MB

# Step 6: Statistical summary

In [21]:
pd.set_option("display.float_format", "{:.2f}".format)

In [22]:
train.describe()

              id  store_nbr      sales  onpromotion
count 3000888.00 3000888.00 3000888.00   3000888.00
mean  1500443.50      27.50     357.78         2.60
std    866281.89      15.59    1102.00        12.22
min         0.00       1.00       0.00         0.00
25%    750221.75      14.00       0.00         0.00
50%   1500443.50      27.50      11.00         0.00
75%   2250665.25      41.00     195.85         0.00
max   3000887.00      54.00  124717.00       741.00

# Step 7: Check missing values

In [25]:
train.isnull().sum()

id             0
date           0
store_nbr      0
family         0
sales          0
onpromotion    0
dtype: int64

In [26]:
stores.isnull().sum()

store_nbr    0
city         0
state        0
type         0
cluster      0
dtype: int64

In [27]:
holidays.isnull().sum()

date           0
type           0
locale         0
locale_name    0
description    0
transferred    0
dtype: int64

In [28]:
oil.isnull().sum()

date           0
dcoilwtico    43
dtype: int64

In [30]:
oil[oil["dcoilwtico"].isnull()]

            date  dcoilwtico
0     2013-01-01         NaN
14    2013-01-21         NaN
34    2013-02-18         NaN
63    2013-03-29         NaN
104   2013-05-27         NaN
132   2013-07-04         NaN
174   2013-09-02         NaN
237   2013-11-28         NaN
256   2013-12-25         NaN
261   2014-01-01         NaN
274   2014-01-20         NaN
294   2014-02-17         NaN
338   2014-04-18         NaN
364   2014-05-26         NaN
393   2014-07-04         NaN
434   2014-09-01         NaN
497   2014-11-27         NaN
517   2014-12-25         NaN
522   2015-01-01         NaN
534   2015-01-19         NaN
554   2015-02-16         NaN
588   2015-04-03         NaN
624   2015-05-25         NaN
653   2015-07-03         NaN
699   2015-09-07         NaN
757   2015-11-26         NaN
778   2015-12-25         NaN
783   2016-01-01         NaN
794   2016-01-18         NaN
814   2016-02-15         NaN
843   2016-03-25         NaN
889   2016-05-30         NaN
914   2016-07-04         NaN
959   2016-09-05         NaN
1017  2016-11-24         NaN
1039  2016-12-26         NaN
1044  2017-01-02         NaN
1054  2017-01-16         NaN
1079  2017-02-20         NaN
1118  2017-04-14         NaN
1149  2017-05-29         NaN
1174  2017-07-03         NaN
1175  2017-07-04         NaN

In [31]:
oil.isnull().sum() / len(oil) * 100

date         0.00
dcoilwtico   3.53
dtype: float64

In [37]:
oil["dcoilwtico"] = oil["dcoilwtico"].ffill().bfill()

In [38]:
oil.isnull().sum()

date          0
dcoilwtico    0
dtype: int64

In [29]:
transactions.isnull().sum()

date            0
store_nbr       0
transactions    0
dtype: int64

# Step 8: Check duplicate rows

In [39]:
print("Train:", train.duplicated().sum())
print("Stores:", stores.duplicated().sum())
print("Holidays:", holidays.duplicated().sum())
print("Oil:", oil.duplicated().sum())
print("Transactions:", transactions.duplicated().sum())

Train: 0
Stores: 0
Holidays: 0
Oil: 0
Transactions: 0

# Step 9: Convert dates

In [40]:
train["date"] = pd.to_datetime(train["date"])
holidays["date"] = pd.to_datetime(holidays["date"])
oil["date"] = pd.to_datetime(oil["date"])
transactions["date"] = pd.to_datetime(transactions["date"])

# Step 10: Find the date range

In [41]:
print("Start:", train["date"].min())
print("End:", train["date"].max())

Start: 2013-01-01 00:00:00
End: 2017-08-15 00:00:00

# Step 11: Count unique values

In [42]:
print("Stores:", train["store_nbr"].nunique())
print("Product Families:", train["family"].nunique())
print("Total Records:", len(train))

Stores: 54
Product Families: 33
Total Records: 3000888

# Step 12: Explore the target variable

In [43]:
train["sales"].describe()

count   3000888.00
mean        357.78
std        1102.00
min           0.00
25%           0.00
50%          11.00
75%         195.85
max      124717.00
Name: sales, dtype: float64

In [45]:
# check the negative sales
(train["sales"] < 0).sum()

np.int64(0)